logging:
    config: classpath:logback-boot.xml
spring:
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
    thymeleaf:
        cache: false
#分页配置
pagehelper:
    #分页时需要返回总页数据及总行数 isCount = true为需要返回，expireAfterAccess总数缓存时间(单位秒，距最后一次访问时间)，maximumSize可缓存的记录数
    count:
        isCount: true
        expireAfterAccess: 10
        maximumSize: 1000
    #如果输入非法则默认但第一页
    defaultPageNo: 1
    #如果如果输入非法则默认页大小
    defaultPageSize: 10
## 数据源配置
datasource:
    url: jdbc:mysql://119.29.26.226:3306/osram?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
